<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Image, FileAudio, FileVideo, FileText, Search } from 'lucide-vue-next'
import type { PluginHostContext } from './shims'
import type { MediaAsset, MediaListQuery, MediaType } from './types'
import MediaGrid from './components/MediaGrid.vue'
import MediaFilters from './components/MediaFilters.vue'
import MediaDetailDrawer from './components/MediaDetailDrawer.vue'

const props = defineProps<{ hostContext: PluginHostContext }>()

const api = computed(() => props.hostContext.api)
const assets = ref<MediaAsset[]>([])
const loading = ref(false)
const error = ref<string | null>(null)
const query = ref<MediaListQuery>({ page: 1, perPage: 24, mediaType: '', pluginSlug: '', search: '' })
const total = ref(0)
const selected = ref<MediaAsset | null>(null)

async function load(): Promise<void> {
    loading.value = true
    error.value = null
    try {
        const params = new URLSearchParams()
        params.set('page', String(query.value.page ?? 1))
        params.set('per_page', String(query.value.perPage ?? 24))
        if (query.value.mediaType) params.set('type', query.value.mediaType)
        if (query.value.pluginSlug) params.set('plugin', query.value.pluginSlug)
        if (query.value.search) params.set('search', query.value.search)
        const response = await api.value.get<{ data: MediaAsset[]; meta: { total: number } }>(
            `/media?${params.toString()}`,
        )
        assets.value = response.data.data
        total.value = response.data.meta.total
    } catch (e) {
        error.value = e instanceof Error ? e.message : String(e)
    } finally {
        loading.value = false
    }
}

function setType(type: MediaType | ''): void {
    query.value = { ...query.value, mediaType: type, page: 1 }
    void load()
}

function setSearch(search: string): void {
    query.value = { ...query.value, search, page: 1 }
    void load()
}

function select(asset: MediaAsset): void {
    selected.value = asset
}

function closeDrawer(): void {
    selected.value = null
}

onMounted(load)
</script>

<template>
    <div class="flex flex-col gap-6 text-foreground">
        <header class="flex flex-col gap-2">
            <h2 class="text-lg font-semibold">Media Archive</h2>
            <p class="text-sm text-muted-foreground">
                {{ total }} {{ total === 1 ? 'asset' : 'assets' }} generated by your agents.
            </p>
        </header>

        <MediaFilters
            :type="query.mediaType ?? ''"
            :search="query.search ?? ''"
            @update:type="setType"
            @update:search="setSearch"
        />

        <div v-if="loading" class="text-sm text-muted-foreground">Loading media…</div>
        <div v-else-if="error" class="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">
            Failed to load media: {{ error }}
        </div>
        <MediaGrid v-else :assets="assets" @select="select" />

        <MediaDetailDrawer v-if="selected" :asset="selected" @close="closeDrawer" />

        <!--
            Kept for design-system parity with the host SPA: the icon set is
            the only stylable surface the host passes through, so we import
            it here to keep `npm run lint` happy even if a future redesign
            adds quick-type pills above the grid.
        -->
        <div class="hidden">
            <Image class="h-4 w-4" />
            <FileAudio class="h-4 w-4" />
            <FileVideo class="h-4 w-4" />
            <FileText class="h-4 w-4" />
            <Search class="h-4 w-4" />
        </div>
    </div>
</template>